# default Ubuntu image
ARG DEV_CONTAINER_TAG
FROM ghcr.io/amidg/dev_base:${DEV_CONTAINER_SHA} AS base

# setup ROS2
WORKDIR /app
COPY ./scripts/install_ros2.sh .
RUN bash ./install_ros2.sh


# NVDA Image
FROM ghcr.io/amidg/dev_base_gpu:${DEV_CONTAINER_SHA} AS gpu_base

# setup ROS2
WORKDIR /app
COPY ./scripts/install_ros2.sh .
RUN bash ./install_ros2.sh
