# TODO:
# - Introduce .env file for configurations
services:
  # intel gpu top
  intel_gpu_top:
    extends:
      file: base.yml
      service: base_igpu
    container_name: intel_gpu_top
    profiles:
      - igpu_top
    image: ghcr.io/amidg/intel_gpu_tools:latest

  # intel igpu deepseek
  intel_gpu_deepseek:
    extends:
      file: base.yml
      service: base_igpu
    profiles:
      - igpu_deepseek
    build:
      context: ./ai
      dockerfile: Dockerfile.intel_gpu.deepseek
      target: base
    container_name: igpu_deepseek
