FROM ghcr.io/amidg/intel_gpu_tools:latest AS base

# install venv
RUN apt update -qqy && \
    apt install -qqy python3-venv

# create virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV --system-site-packages --symlinks
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
#RUN echo "source $VIRTUAL_ENV/bin/activate" >> ~/.bashrc

