#FROM intelanalytics/ipex-llm-serving-xpu:latest AS base
FROM intelanalytics/ipex-llm-xpu:latest AS base

RUN pip install --pre --upgrade ipex-llm[cpp]

RUN echo "export USE_XETLA=OFF" >> ~/.bashrc
RUN echo "export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=0" >> ~/.bashrc
RUN echo "export SYCL_CACHE_PERSISTENT=1" >> ~/.bashrc
RUN echo "export ENABLE_SDP_FUSION=0" >> ~/.bashrc

RUN echo "export OLLAMA_NUM_GPU=999" >> ~/.bashrc
RUN echo "export no_proxy=localhost,127.0.0.1" >> ~/.bashrc
RUN echo "export ZES_ENABLE_SYSMAN=1" >> ~/.bashrc
RUN echo "export ONEAPI_DEVICE_SELECTOR=level_zero:0" >> ~/.bashrc

CMD ["./ollama serve"]
