FROM intelanalytics/ipex-llm-xpu:latest AS base

# initialize ollama
RUN pip install --pre --upgrade ipex-llm[cpp] && \
    init-ollama

# copy startup script
COPY ./start_ollama.sh .


# use ollam webui
FROM base AS webui

# install webui
RUN pip install -U open-webui

CMD ["open-webui serve"]
