services:
  local-deep-research:
    image: localdeepresearch/local-deep-research
    networks:
      - ldr-network
    ports:
      - 5000:5000
    environment:
      # ============================================================================
      # IMPORTANT: Almost all settings can be configured through the web interface.
      #
      # Environment variables FORCE settings and prevent ANY changes through the UI.
      # These are NOT defaults - they are permanent overrides that lock the setting.
      # Only use environment variables if you want to enforce specific settings
      # that users should NEVER be able to change.
      #
      # After starting the container, configure your settings at:
      # http://localhost:5000/settings
      # ============================================================================

      # ============================================================================
      # DOCKER-SPECIFIC SETTINGS (Forced for good reasons!)
      # These settings are forced to ensure proper Docker operation:
      # - Prevents accidental misconfiguration that would break the container
      # - Ensures consistency between Docker configuration and application settings
      # - Users can still change ports via Docker's port mapping (see below)
      # ============================================================================
      - LDR_WEB_HOST=0.0.0.0                 # Must bind to all interfaces for Docker networking
      - LDR_WEB_PORT=5000                    # Internal port must match Docker's expectation
      - LDR_DATA_DIR=/data                   # Must match the volume mount point

      # ============================================================================
      # TO CHANGE PORTS: Use Docker port mapping, NOT the settings above!
      # Example - to expose on port 8080 instead of 5000:
      #   ports:
      #     - "8080:5000"  # Maps host port 8080 to container port 5000
      #
      # This is the Docker way and avoids configuration mismatches.
      # ============================================================================

      # ============================================================================
      # OPTIONAL: Service endpoints for docker-compose setup
      # WARNING: These will lock the settings and prevent changes through the UI!
      # Uncomment these if you want to enforce these service endpoints.
      # Otherwise, configure them through the web interface after startup.
      # ============================================================================
      - LDR_LLM_OLLAMA_URL=http://192.168.0.171:11434
      # - LDR_SEARCH_ENGINE_WEB_SEARXNG_DEFAULT_PARAMS_INSTANCE_URL=http://searxng:8080

      # ============================================================================
      # ADVANCED: Uncomment ONLY if you need to enforce/lock these settings
      # WARNING: This will disable UI configuration for these settings!
      # ============================================================================
      - LDR_LLM_PROVIDER=ollama              # Lock the LLM provider
      - LDR_LLM_MODEL=gemma3:27b              # Lock the model selection
      #- LDR_LLM_OPENAI_API_KEY=sk-...        # Lock OpenAI API key
      #- LDR_LLM_ANTHROPIC_API_KEY=sk-ant-... # Lock Anthropic API key
    volumes:
      - ldr_data:/data
      - ldr_scripts:/scripts
      - local_collections:/local_collections
      #- ./local_collections/personal_notes:/local_collections/personal_notes/
      #- ./local_collections/project_docs:/local_collections/project_docs/
      #- ./local_collections/research_papers:/local_collections/research_papers/
    restart: unless-stopped
    depends_on:
      searxng:
        condition: service_started

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    networks:
      - ldr-network
    volumes:
      - searxng_data:/etc/searxng
    restart: unless-stopped

volumes:
  ldr_data:
  ldr_scripts:
  local_collections:
  searxng_data:
networks:
  ldr-network:
