name: Build dockerfiles

on:
  push:
    branches:
      - main
      - dev-tools
    tags:
      - 'v*.*.*'

jobs:
  # generic containers for daily use
  build_generic_containers:
    uses: amidg/workflows/.github/workflows/build_container.yml@main
    strategy:
      matrix:
        container:
          - name: cups_samsung
            path: ./cups-samsung
            file: Dockerfile
          - name: intel_gpu_tools
            path: ./tools
            file: Dockerfile.intel_gpu_top
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      container_tag: ${{ github.sha }}
    secrets:
      PODMAN_TOKEN: ${{ secrets.PODMAN_TOKEN }}

  # Build Development Artifacts
  build_debian_packages:
    uses: amidg/workflows/.github/workflows/deb_package.yml@main
    strategy:
      matrix:
        package:
          - name: opencv
            path: ./development/packages/opencv
    with:
      name: ${{ matrix.package.name }}
      scripts_path: ${{ matrix.package.path }}

  # Development containers
  build_development_containers:
    uses: amidg/workflows/.github/workflows/build_container.yml@main
    strategy:
      matrix:
        container:
          - name: dev_base
            path: ./development
            file: Dockerfile
            target: base
          - name: dev_base_gpu
            path: ./development
            file: Dockerfile
            target: gpu_base
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      build_target: ${{ matrix.container.target }}
      container_tag: ${{ github.sha }}
    secrets:
      PODMAN_TOKEN: ${{ secrets.PODMAN_TOKEN }}

  # ROS2 containers
  build_ros_containers:
    uses: amidg/workflows/.github/workflows/build_dependable_container.yml@main
    needs: build_development_containers
    strategy:
      matrix:
        container:
          - name: ros2
            path: ./development
            file: Dockerfile.ros2
            target: base
          - name: ros2_gpu
            path: ./development
            file: Dockerfile.ros2
            target: gpu_base
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      build_target: ${{ matrix.container.target }}
      commit_sha: ${{ github.sha }}
    secrets:
      PODMAN_TOKEN: ${{ secrets.PODMAN_TOKEN }}

  # OpenCV Containers
  build_opencv_containers:
    uses: amidg/workflows/.github/workflows/build_dependable_container.yml@main
    needs: [build_development_containers, build_debian_packages, build_ros_containers]
    strategy:
      matrix:
        container:
          - name: opencv
            path: ./development
            file: Dockerfile.cv
            target: opencv
          - name: opencv_gpu
            path: ./development
            file: Dockerfile.cv
            target: opencv_gpu
          - name: ros2_cv
            path: ./development
            file: Dockerfile.cv
            target: ros2_cv
          - name: ros2_gpu_cv
            path: ./development
            file: Dockerfile.cv
            target: ros2_gpu_cv
    with:
      container_name: ${{ matrix.container.name }}
      container_path: ${{ matrix.container.path }}
      container_file: ${{ matrix.container.file }}
      build_target: ${{ matrix.container.target }}
      commit_sha: ${{ github.sha }}
      download_artifact: true
      artifact_name: opencv
    secrets:
      PODMAN_TOKEN: ${{ secrets.PODMAN_TOKEN }}
