name: Build dockerfiles

# Trigger this workflow on pushes to any branch and tags matching v*.*.*
on:
  push:
    branches: [ '*' ]
    tags: [ 'v*.*.*' ]

jobs:
  # generic containers for daily use
  #build_generic_containers:
  #  uses: amidg/workflows/.github/workflows/build_container.yml@main
  #  strategy:
  #    matrix:
  #      container:
  #        - name: cups_samsung
  #          path: ./cups-samsung
  #          file: Dockerfile
  #        - name: intel_gpu_tools
  #          path: ./tools
  #          file: Dockerfile.intel_gpu_top
  #  with:
  #    container_name: ${{ matrix.container.name }}
  #    container_path: ${{ matrix.container.path }}
  #    container_file: ${{ matrix.container.file }}
  #    container_tag: ${{ github.sha }}
  #  secrets:
  #    CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

  # Build Development Container
  # This container provides my custom setup for C++ and Python development
  build_development:
    uses: amidg/workflows/.github/workflows/build_docker_multiarch.yml@main
    strategy:
      matrix:
        include:
          - container_name: developer
            build_target: base
    with:
      container_name: ${{ matrix.container_name }}
      container_file: development/Containerfile
      container_tag: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}
      build_target: ${{ matrix.build_target }}
    secrets:
      CONTAINER_TOKEN: ${{ secrets.CONTAINER_TOKEN }}

